[book]
authors = ["Eric Volpert"]
language = "en"
multilingual = false
src = "src"
title = "Practical Observability"

[output.html]
mathjax-support = true
no-section-label = true
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 2         # the depth to start folding
